#--- Application name
spring.application.name=library
#--- Active profile
spring.profiles.active=dev

#---
jwt.config.issuer=com.t0khyo.library
jwt.config.token-expiration-seconds=3600
jwt.config.publicKey=classpath:certs/public.pem
jwt.config.privateKey=classpath:certs/private.pem

spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data/data.sql
